export {default as kfm_logo} from "./logo_kimia_farma_mobile.png";
export {default as visa_mandiri} from "./visa_mandiri.png";
export { default as clinic_reservation } from "./clinic_reservation.png";
export { default as lab_test } from "./lab_test.png";
export { default as vitamin_suplemen } from "./vitamin_suplemen.png";
export { default as dettol_50ml } from "./dettol_50ml.png";
export { default as shipper_default } from "./shipper_default.png";
export { default as cart_icon } from "./cart_icon.png";
export { default as jne } from "./jne.png";
export { default as grab } from "./grab.png";
export { default as gojek } from "./gojek.png";
export { default as self_pickup } from "./self_pickup.png";
export { default as warning_icon } from "./warning_icon.png";